### ISSUE TITLE
Unable to remove guaranteedAddress

### ISSUE THREAD

**Issue by adamdossa** [status-im/status-network-token#101] opened 2017-06-15 16:17 UTC
In:
https://github.com/status-im/status-network-token/blob/master/contracts/StatusContribution.sol#L163
in states that to remove a guaranteedAddress, you would set the _limit to 0.

However, at:
https://github.com/status-im/status-network-token/blob/master/contracts/StatusContribution.sol#L167
there is a require that will throw if _limit is 0.

Fix:
Either modify the require to allow _limit == 0, or change the relevant comment (depending on whether you wish to allow guaranteedAddresses to be removed).

**Comment by nfnty** [comment] 2017-06-15 17:15
Duplicate of #97.

**Closed** 2017-06-16 06:27 UTC
